server.port=8082
#---
#nacos
#---
###################################################
# 1. ?????????????????
###################################################
# ????Nacos ??????ID????????????
spring.application.name=llm-callback

###################################################
# 2. Nacos ????????? 3.0.3 ???
###################################################
# Nacos ???????????????IP??????VIP????IP:???
spring.cloud.nacos.discovery.server-addr=192.168.0.101:8848,192.168.0.132:8848,192.168.0.112:8848
# ???????public??????????????UUID
# spring.cloud.nacos.discovery.namespace=public
# ?????DEFAULT_GROUP
spring.cloud.nacos.discovery.group=DEFAULT_GROUP
# ?????????true?????
spring.cloud.nacos.discovery.enabled=true
# ?????????true?????
spring.cloud.nacos.discovery.register-enabled=true

###################################################
# 3. ???????????????????????
###################################################
# ???????1????????????
spring.cloud.nacos.discovery.weight=1
# ?????????true??????Nacos?????
spring.cloud.nacos.discovery.ephemeral=true
# ?????????TCP????HTTP?
spring.cloud.nacos.discovery.health-check-type=TCP
# ??????????
spring.cloud.nacos.discovery.health-check-interval=5000

###################################################
# 4. ???Nacos ??????????????
###################################################
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos

###################################################
# 5. ?????????????????
###################################################
#server.servlet.context-path=/api
logging.level.root=INFO



###################################################33
#sentinel
##################################################33

# ======================
# Sentinel ???
# ======================
# Sentinel Dashboard ??????????
spring.cloud.sentinel.transport.dashboard=127.0.0.1:8083
# ???? Dashboard ???????????+1?
spring.cloud.sentinel.transport.port=8719
# ?????? Dashboard??????????????
spring.cloud.sentinel.eager=true

# ======================
# ?????Nacos??????
# ======================

# ---- ???? ----
spring.cloud.sentinel.datasource.flow-rules.nacos.server-addr=127.0.0.1:8848
spring.cloud.sentinel.datasource.flow-rules.nacos.data-id=${spring.application.name}-flow-rules
spring.cloud.sentinel.datasource.flow-rules.nacos.group-id=DEFAULT_GROUP
spring.cloud.sentinel.datasource.flow-rules.nacos.rule-type=flow

# ---- ?????? ----
spring.cloud.sentinel.datasource.degrade-rules.nacos.server-addr=127.0.0.1:8848
spring.cloud.sentinel.datasource.degrade-rules.nacos.data-id=${spring.application.name}-degrade-rules
spring.cloud.sentinel.datasource.degrade-rules.nacos.group-id=DEFAULT_GROUP
spring.cloud.sentinel.datasource.degrade-rules.nacos.rule-type=degrade

# ---- ????????----
spring.cloud.sentinel.datasource.system-rules.nacos.server-addr=127.0.0.1:8848
spring.cloud.sentinel.datasource.system-rules.nacos.data-id=${spring.application.name}-system-rules
spring.cloud.sentinel.datasource.system-rules.nacos.group-id=DEFAULT_GROUP
spring.cloud.sentinel.datasource.system-rules.nacos.rule-type=system





#########################################33#########
# redis
###################################################3
# Redis ?? (Spring Boot 3.x ???)
spring.data.redis.password=nacos
# Sentinel ????? (??? sentinel.conf ?? mymaster ????)
spring.data.redis.sentinel.master=mymaster
# Sentinel ????
spring.data.redis.sentinel.nodes=192.168.0.101:26379,192.168.0.132:26380,192.168.0.112:26381
# ??????????
spring.data.redis.timeout=2000
# ????? Redis ???????0????????????
spring.data.redis.database=0
# Lettuce ?????
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2




# ======================
# ???OpenAI ?????
# ======================
spring.ai.openai.base-url=https://dashscope.aliyuncs.com
spring.ai.openai.api-key=sk-568e9246df2147ad9f013dc9a3099927
spring.ai.openai.chat.options.model=qwen-plus
spring.ai.openai.chat.completions-path=/compatible-mode/v1/chat/completions

#------------------------------
ollama.base-url=http://192.168.0.101:11434
ollama.model.embed=bge-m3:latest
ollama.timeout-ms=60000

#??
spring.datasource.master.jdbc-url=jdbc:postgresql://192.168.0.101:5432/ai_test
spring.datasource.master.username=postgres
spring.datasource.master.password=123456
spring.datasource.master.driver-class-name=org.postgresql.Driver

#=======??=======================
spring.datasource.slave.jdbc-url=jdbc:postgresql://192.168.0.132:5432/ai_test
spring.datasource.slave.username=postgres
spring.datasource.slave.password=123456
spring.datasource.slave.driver-class-name=org.postgresql.Driver


# ======================
# MCP Client?Spring AI 2.0?
# ======================
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.name=search
spring.ai.mcp.client.version=1.0.0

spring.ai.mcp.client.streamable-http.connections.search.url=http://192.168.0.101:8000/mcp
spring.ai.mcp.client.type=SYNC
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.org.springframework.ai.chat.client=TRACE

mcp.server.url=http://192.168.0.101:8000/mcp

# ???????? 8?
spring.task.execution.pool.core-size=5
# ???????? Integer.MAX_VALUE??????
spring.task.execution.pool.max-size=20
# ??????? Integer.MAX_VALUE??????
spring.task.execution.pool.queue-capacity=100
# ??????????? 60s?
spring.task.execution.pool.keep-alive=60s
# ???????????????????
spring.task.execution.thread-name-prefix=async-task-

#rabbitmq
#spring.rabbitmq.host=192.168.253.128
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.virtual-host=/
#
#spring.rabbitmq.requested-heartbeat=30s
#spring.rabbitmq.connection-timeout=5s
#
#spring.rabbitmq.publisher-confirm-type=correlated
#spring.rabbitmq.publisher-returns=true
#
#spring.rabbitmq.template.mandatory=true
#spring.rabbitmq.template.receive-timeout=5000
#
#spring.rabbitmq.listener.simple.concurrency=5
#spring.rabbitmq.listener.simple.max-concurrency=20
#spring.rabbitmq.listener.simple.prefetch=50
#spring.rabbitmq.listener.simple.default-requeue-rejected=false
#spring.rabbitmq.listener.simple.acknowledge-mode=manual
#
#spring.rabbitmq.listener.simple.retry.enabled=true